### ISSUE TITLE
Incorrect description of join condition in INNER_JOIN.md

### ISSUE THREAD

**Issue by TylerBrock** [weinberg/SQLToy#2]
In INNER_JOIN.md you state:

> If we want to know the name of the department each employee is in then we want our condition to filter out only those rows where the employee.department_id column is equal to the department.id column.

What I *think* you meant to say is:

> If we want to know the name of the department each employee is in then we want our condition to select only those rows where the employee.department_id column is equal to the department.id column.

OR

> If we want to know the name of the department each employee is in then we want our condition to filter out those rows where the employee.department_id column does not equal to the department.id column.

**Comment by weinberg** [comment]
Ah yes thank you! Will fix.
